# Generated by Django 3.1.1 on 2020-10-18 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_vacancies', '0003_auto_20200917_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='published_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=500)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_vacancies.vacancy')),
            ],
        ),
    ]
