# Generated by Django 3.1.1 on 2020-10-20 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_vacancies', '0004_auto_20201018_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('secondname', models.CharField(max_length=30)),
                ('job_status', models.CharField(max_length=30)),
                ('waiting_salary', models.IntegerField()),
                ('qualification', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=150)),
                ('work_experience', models.CharField(max_length=200)),
                ('portfolio_link', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                to='app_vacancies.specialty')),
            ],
        ),
    ]
