# Generated by Django 3.1.1 on 2020-10-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vacancies', '0006_auto_20201020_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='job_status',
            field=models.CharField(choices=[
                ('Ищу работу', 'Ищу работу'),
                ('Открыт к предложениям', 'Открыт к предложениям'),
                ('Не ищу работу', 'Не ищу работу')
            ], default='1', max_length=30),
        ),
        migrations.AlterField(
            model_name='resume',
            name='qualification',
            field=models.CharField(choices=[
                ('Средний (middle)', 'Средний (middle)'),
                ('Младший (junior)', 'Младший (junior)'),
                ('Старший (senior)', 'Старший (senior)')
            ], default='1', max_length=30),
        ),
    ]
